// Generated by CoffeeScript 1.4.0
(function() {
  var Cache, helper, key, val, watch;

  helper = require('./helper');

  Cache = require('./cache');

  watch = require('./watch');

  helper.cache = function(options) {
    return new Cache();
  };

  for (key in watch) {
    val = watch[key];
    helper[key] = val;
  }

  module.exports = helper;

}).call(this);
