// Generated by CoffeeScript 1.4.0
(function() {
  var Cache, helper;

  helper = require('./helper');

  Cache = require('./cache');

  helper.cache = function(options) {
    return new Cache();
  };

  module.exports = helper;

}).call(this);
