// Generated by CoffeeScript 1.4.0
(function() {
  var Monitor, fs, helper, path, watch;

  fs = require('fs');

  path = require('path');

  helper = require('./helper');

  Monitor = (function() {

    function Monitor(rootPath, options, files) {
      this.rootPath = rootPath;
      this.options = options;
      if (files == null) {
        files = [];
      }
      this.files = {};
    }

    return Monitor;

  })();

  watch = function(rootPath, options, cb) {
    if (arguments.length === 2) {
      cb = options;
      options = {};
    }
    return helper.readdir(rootpath, options, function(err, files) {
      if (err) {
        return cb(err);
      } else {
        return cb(null, new Monitor(rootPath, options, files));
      }
    });
  };

  module.exports = {
    watch: watch
  };

}).call(this);
